dist: xenial

language: go

go:
  - "1.12.x"

install:
  # The repo go langserver must be located under '$GOPATH/src/golang.org/x/tools', however we can't reset the clone
  # path. So we have to clone the repo manually.
  - git clone https://github.com/elastic/go-langserver $GOPATH/src/golang.org/x/tools
  - if [ $TRAVIS_PULL_REQUEST != "false" ]; then
    git fetch -q origin +refs/pull/$TRAVIS_PULL_REQUEST/merge:;
    git checkout -qf FETCH_HEAD;
    fi
  - cd $GOPATH/src/golang.org/x/tools

git:
  depth: 1

env:
  - GO111MODULE=off GOPROXY=https://proxy.golang.org


before_install:
  - go get golang.org/x/sync/errgroup

matrix:
  fast_finish: true
  include:
    - name: Unit Tests & Package | Linux x64
      os: linux
      script:
        - go test ./internal/lsp
        - go build -o ../go-langserver-linux-amd64 $GOPATH/src/golang.org/x/tools/cmd/gopls
        - curl -o ../go1.12.7.linux-amd64.tar.gz https://dl.google.com/go/go1.12.7.linux-amd64.tar.gz
        - tar xzf ../go1.12.7.linux-amd64.tar.gz -C ../
        - mkdir build
        - tar -zcf ./build/go-langserver-linux-amd64.tar.gz ../go-langserver-linux-amd64 ../go
      deploy:
        provider: releases
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        verbose: true
        file: $GOPATH/src/golang.org/x/tools/build/*
        file_glob: true
        name: $TRAVIS_TAG
        draft: false
        prerelease: false
        overwrite: true
        on:
          all_branches: true
          tags: true

    - name: Unit Tests & Package | Linux x86
      os: linux
      script:
        - go test ./internal/lsp
        - go build -o ../go-langserver-linux-386 $GOPATH/src/golang.org/x/tools/cmd/gopls
        - curl -o ../go1.12.7.linux-386.tar.gz https://dl.google.com/go/go1.12.7.linux-386.tar.gz
        - tar xzf ../go1.12.7.linux-386.tar.gz -C ../
        - mkdir build
        - tar -zcf ./build/go-langserver-linux-386.tar.gz ../go-langserver-linux-386 ../go
      deploy:
        provider: releases
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        verbose: true
        file: $GOPATH/src/golang.org/x/tools/build/*
        file_glob: true
        name: $TRAVIS_TAG
        draft: false
        prerelease: false
        overwrite: true
        on:
          all_branches: true
          tags: true

    - name: Unit Tests & Package | OSX
      os: osx
      script:
        - go test ./internal/lsp
        - go build -o ../go-langserver-darwin-amd64 $GOPATH/src/golang.org/x/tools/cmd/gopls
        - curl -o ../go1.12.7.darwin-amd64.tar.gz https://dl.google.com/go/go1.12.7.darwin-amd64.tar.gz
        - tar xzf ../go1.12.7.darwin-amd64.tar.gz -C ../
        - mkdir build
        - tar -zcf ./build/go-langserver-darwin-amd64.tar.gz ../go-langserver-darwin-amd64 ../go
      deploy:
        provider: releases
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        verbose: true
        file: $GOPATH/src/golang.org/x/tools/build/*
        file_glob: true
        name: $TRAVIS_TAG
        draft: false
        prerelease: false
        overwrite: true
        on:
          all_branches: true
          tags: true
